[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Posts"
  pageRef = "/posts/"
  weight = 20

[[main]]
  name = "Alibaba Store"
  url = "https://mecrt.en.alibaba.com/"
  weight = 30
