colorScheme = "blowfish"
defaultAppearance = "light"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = false
mainSections = ["posts"]
smartTOC = true
brandName = "<strong>Catholic Religious Gifts Guide</strong> - RosarySupply.com"
copyright = "<a href='https://ctoco.com/'>CTOCO-Catholic Rosary</a>"

[homepage]
layout = "background"
subtitle = "Catholic Religious Gifts Guide - RosarySupply.com"
showRecent = true
showRecentItems = 6
showReadingTime = true

[article]
showDate = true
showAuthor = true
showBreadCrumbs = true
showSummary = true
showPagination = true
showReadingTime = true
showWordCount = true
showTaxonomies = true
showHero = true
heroStyle = "background"
showTableOfContents = true

[list]
showSummary = true
showCards = true
cardView = true
groupByYear = false
