colorScheme = "blowfish"
defaultAppearance = "light"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = false
mainSections = ["posts"]
smartTOC = true
copyright = "© { year } [CTOCO-Catholic Rosary](https://ctoco.com/)"

[homepage]
layout = "background"
showRecent = true
showRecentItems = 6
showReadingTime = true

[article]
showDate = true
showAuthor = true
showBreadCrumbs = true
showSummary = true
showPagination = true
showReadingTime = true
showWordCount = true
showTaxonomies = true
showHero = true
heroStyle = "background"
showTableOfContents = true

[list]
showSummary = true
showCards = true
cardView = true
groupByYear = false
